APP_MODULES := application sdl-1.2 sdl_main
APP_ABI := armeabi
APP_OPTIM := release

SDL_JAVA_PACKAGE_PATH := anise_port_android
SDL_CURDIR_PATH := anise.port.android
SDL_VERSION := 1.2
SDL_TRACKBALL_KEYUP_DELAY := 1
SDL_VIDEO_RENDER_RESIZE := 1
SDL_VIDEO_RENDER_RESIZE_KEEP_ASPECT := 0
SDL_ADDITIONAL_CFLAGS :=  \
	-DSDL_ANDROID_KEYCODE_0=SPACE \
	-DSDL_ANDROID_KEYCODE_1=RETURN \
	-DSDL_ANDROID_KEYCODE_2=PLUS \
	-DSDL_ANDROID_KEYCODE_3=MINUS \
	-DSDL_ANDROID_KEYCODE_4=F11 \
	-DSDL_ANDROID_KEYCODE_5=ESCAPE \
	-DSDL_ANDROID_KEYCODE_6=F5 \
	-DSDL_ANDROID_KEYCODE_7=F6 \
	-DSDL_ANDROID_KEYCODE_8=F7 \
	-DSDL_ANDROID_KEYCODE_9=F8 \
	-DSDL_ANDROID_SCREENKB_KEYCODE_0=RETURN \
	-DSDL_ANDROID_SCREENKB_KEYCODE_1=BACKSPACE \
	-DSDL_ANDROID_SCREENKB_KEYCODE_2=SPACE \
	-DSDL_ANDROID_SCREENKB_KEYCODE_3=ESCAPE \

